name: CI

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: pnpm i --frozen-lockfile

            - name: Run CI
              run: pnpm test
